"""Live state REST endpoints and the WebSocket upgrade route."""

from datetime import datetime
from typing import Literal

from fastapi import APIRouter, Depends, HTTPException, WebSocket, WebSocketDisconnect
from pydantic import BaseModel

from lineage.api.deps import AppState, get_app_state
from lineage.datagen.models import RunConfig
from lineage.replay.engine import ReplayEngine
from lineage.replay.run_data import RunData
from lineage.twin.ingest import from_generated_run

router = APIRouter()


@router.get("/api/runs")
def list_runs(state: AppState = Depends(get_app_state)) -> list[dict]:
    if not state.runs_root.exists():
        return []
    return [{"run_id": p.name} for p in sorted(state.runs_root.iterdir()) if p.is_dir()]


class ReplayControlRequest(BaseModel):
    action: Literal["load", "play", "pause", "step", "seek", "set_speed"]
    run_id: str | None = None
    timestamp: datetime | None = None
    speed_multiplier: float | None = None


def load_run_into_state(state: AppState, run_id: str) -> None:
    """The full 'load' side effect: point the replay engine and genealogy
    cache at `run_id`, and drop every cache that was built against whatever
    run was previously loaded. Shared by the existing action='load' branch
    below and by api/routes/datagen.py's on-demand "Simulate" endpoint,
    which generates a fresh run and then needs this exact same load."""
    if state.line is None:
        raise HTTPException(status_code=404, detail="no line loaded")
    run_dir = state.runs_root / run_id
    if not run_dir.exists():
        raise HTTPException(status_code=404, detail=f"unknown run {run_id!r}")
    run_config_path = run_dir / "run_config.json"
    if not run_config_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"run {run_id!r} has no run_config.json (generated by an older "
            "version of generate_run?)",
        )
    run_config = RunConfig.model_validate_json(run_config_path.read_text())

    run_data = RunData(run_id, run_dir)
    state.engine = ReplayEngine(state.line, run_data, start_time=run_data.start_time)
    # Built once here, not per car-history request -- GET /api/cars/{car_id}
    # only ever reads from this cache.
    state.genealogy_store = from_generated_run(state.line, run_dir, run_config)

    # The prediction ledger is NOT built here -- it's expensive (~105s
    # observed for a 400-car run, assessing every car against every
    # inspection station it reached) and 'load' is expected to stay
    # fast. api/routes/predict.py builds and caches it lazily on first
    # request instead. Just record where this run lives, and drop any
    # ledger cached for a previously-loaded run.
    state.current_run_dir = run_dir
    state.prediction_ledger = None
    # Same reasoning: real per-car work, built lazily by api/routes/act.py
    # and Plant Manager's recurring-root-cause report on first request,
    # and an assignment refers to a specific run's alert that no longer
    # exists once that run is gone.
    state.trace_results = None
    state.act_proposals = None
    state.issue_assignments = {}


@router.post("/api/replay/control")
def replay_control(req: ReplayControlRequest, state: AppState = Depends(get_app_state)) -> dict:
    if req.action == "load":
        if req.run_id is None:
            raise HTTPException(status_code=400, detail="run_id required for 'load'")
        load_run_into_state(state, req.run_id)
        return {"ok": True}

    if state.engine is None:
        raise HTTPException(status_code=409, detail="no run loaded; send action='load' first")

    if req.action == "play":
        state.engine.resume()
    elif req.action == "pause":
        state.engine.pause()
    elif req.action == "step":
        state.engine.set_step_mode()
        state.engine.step()
    elif req.action == "seek":
        if req.timestamp is None:
            raise HTTPException(status_code=400, detail="timestamp required for 'seek'")
        # Also pushed into snapshot_history, not just returned -- the
        # background tick loop is the only other thing that ever pushes a
        # snapshot, and only while playing, once per real second. Without
        # this, a seek immediately followed by a role-view poll (exactly
        # what scrubbing the replay position and checking a view does) can
        # read a stale pre-seek snapshot for up to a second, a real bug
        # found while adding the Floor Supervisor alert queue, which is
        # seek-sensitive in exactly this way.
        line_state = state.engine.seek(req.timestamp)
        state.snapshot_history.push(line_state)
    elif req.action == "set_speed":
        if req.speed_multiplier is None:
            raise HTTPException(status_code=400, detail="speed_multiplier required for 'set_speed'")
        state.engine.set_speed(req.speed_multiplier)

    return {"ok": True}


@router.get("/api/cars/{car_id}")
def get_car(car_id: str, state: AppState = Depends(get_app_state)) -> dict:
    """A car's full twin history -- every station passed, readings taken
    there, dwell time. Reads from the cache built at 'load' time; never
    rebuilds the index per request."""
    if state.genealogy_store is None:
        raise HTTPException(status_code=409, detail="no run loaded; send action='load' first")
    try:
        car = state.genealogy_store.car(car_id)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"unknown car {car_id!r}") from None
    return car.model_dump(mode="json")


@router.websocket("/ws/line")
async def ws_line(websocket: WebSocket, state: AppState = Depends(get_app_state)) -> None:
    await state.connection_manager.connect(websocket)
    for snapshot in state.snapshot_history.recent():
        await websocket.send_json(snapshot.model_dump(mode="json"))
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        state.connection_manager.disconnect(websocket)
